language: cpp
compiler:
  - gcc
  - clang
  
branches:
  - master
  - testing

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt56 -y
  - sudo apt-get update -q
  - sudo apt-get install qt56-meta libgtest-dev

script:
  - source /opt/qt56/bin/qt56-env.sh
  - qmake
  - make