language: cpp
compiler:
  - gcc
  - clang
  
branches:
  - master
  - testing

before_install:
  - sudo apt-add-repository ppa:beineri/opt-qt55 -y
  - sudo apt-get update -q
  - sudo apt-get install qt55-meta-minimal qt55multimedia libgtest-dev

script:
  - source /opt/qt55/bin/qt55-env.sh
  - qmake
  - make